name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.2
        with:
          compiler: gcc-latest

      - name: Build
        run: g++ main.cpp -o app

      - name: Run
        run: ./app
