name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify compiler
        run: g++ --version

      - name: Build
        run: g++ -Wall -o app main.cpp

      - name: Run
        run: ./app
