name: LeetCode CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  compile:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install Clang
        run: |
          sudo apt-get update
          sudo apt-get install -y clang

      - name: Show versions
        run: |
          clang++ --version
          node --version

      - name: Compile all LeetCode solutions
        shell: bash
        run: |

          shopt -s globstar nullglob

          total=0
          passed=0
          failed=0

          for file in **/*.cpp
          do

            [[ "$file" == .github/* ]] && continue

            total=$((total+1))

            echo ""
            echo "===================================="
            echo "Compiling $file"

            TMP=$(mktemp --suffix=.cpp)

            cat .github/leetcode_mock.hpp > "$TMP"
            echo >> "$TMP"
            cat "$file" >> "$TMP"
            echo >> "$TMP"
            echo "int main(){return 0;}" >> "$TMP"

            if clang++ \
                -std=c++20 \
                -Wall \
                -Wextra \
                -pedantic \
                "$TMP" \
                -o /tmp/a.out
            then
                echo "PASS"
                passed=$((passed+1))
            else
                echo "FAIL"
                failed=$((failed+1))
            fi

            rm "$TMP"

          done

          echo ""
          echo "=============================="
          echo "Passed : $passed"
          echo "Failed : $failed"
          echo "Total  : $total"
          echo "=============================="

          test $failed -eq 0
